### ISSUE TITLE
Energy function

### ISSUE THREAD

**Issue by ir0nt0ad** [AliMorty/Markov-Random-Field-Project#1]
Hi, just interested in how you came up with the definition of the energy function. Thank you!

**Comment by AliMorty** [comment]
Cool! Thank you!

**Comment by ir0nt0ad** [comment]
Yeah so how did you come up with the formula?

**Comment by AliMorty** [comment]
Thank you for looking at my project!

This project was a part of PGMs class homework and I remember that we
didn't know that much about the theory at that time. We just knew that this
formula is effective for capturing the dependencies in this task. I
think the first term in the energy function can be related to a logarithm
of a normal joint probability distribution for all individual pixels and
the second term is used to capture the dependencies between
neighbor pixels. (i.e. decrease the probability when two adjacent pixels
have different colors.)

I guess this is a Markov network and in this setting, all distributions
should have the Gibbs distribution format. this might be a reason why we
are expecting the second term to have this format. I am not sure about this
sentence at all!)

Because I have done this project in the past, I don't remember the
detail right now. Therefore, I have attached the following document for
more information about the energy function for this particular task. I hope
this helps.

Thank you for your attention and your email.

Bests,
Ali

**Comment by AliMorty** [comment]
In other word,  we want to find the probabilty of occurance of any given
configuration of pixels. Using this probability, we can find the most
likely configuration of unknown pixels. In fact we are using Maximum
likelihood estimation to predict the labels for unknown pixels.

Because our model is MRF, we model the dependencies between any two
adjacent pixels by a multiplication term (second term in energy funcfion).
We also assume that probability  distribution for each pixel is a normal
distribution.

As a result, we have a the probability distobution for occurance of any
particular configuration for pixels. The logarithm of this probability is
that energy function that you mentioned.

You can also look at the my previous email and find a document attached to
it for more information.

Bests,
Ali

**Comment by ir0nt0ad** [comment]
Hey, thanks for the detailed feedback. Unfortunately I can't see the document you said you attached.

**Comment by AliMorty** [comment]
You can find it [Here](https://github.com/AliMorty/AliMorty.github.io/raw/master/files/MRF.pdf)

**Comment by ir0nt0ad** [comment]
Great, thanks again!
